// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class annotation {
        
        private string folderField;
        
        private string filenameField;
        
        private annotationSource sourceField;
        
        private annotationOwner ownerField;
        
        private annotationSize sizeField;
        
        private sbyte segmentedField;
        
        private annotationObject[] objectField;
        
        /// <remarks/>
        public string folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
        
        /// <remarks/>
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        public annotationSource source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public annotationOwner owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        public annotationSize size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public sbyte segmented {
            get {
                return this.segmentedField;
            }
            set {
                this.segmentedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("object")]
        public annotationObject[] @object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class annotationSource {
        
        private string databaseField;
        
        private string annotationField;
        
        private string imageField;
        
        private int flickridField;
        
        /// <remarks/>
        public string database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
            }
        }
        
        /// <remarks/>
        public string annotation {
            get {
                return this.annotationField;
            }
            set {
                this.annotationField = value;
            }
        }
        
        /// <remarks/>
        public string image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        public int flickrid {
            get {
                return this.flickridField;
            }
            set {
                this.flickridField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class annotationOwner {
        
        private string flickridField;
        
        private string nameField;
        
        /// <remarks/>
        public string flickrid {
            get {
                return this.flickridField;
            }
            set {
                this.flickridField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class annotationSize {
        
        private short widthField;
        
        private short heightField;
        
        private sbyte depthField;
        
        /// <remarks/>
        public short width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public short height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public sbyte depth {
            get {
                return this.depthField;
            }
            set {
                this.depthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class annotationObject {
        
        private string nameField;
        
        private string poseField;
        
        private sbyte truncatedField;
        
        private sbyte difficultField;
        
        private annotationObjectBndbox bndboxField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string pose {
            get {
                return this.poseField;
            }
            set {
                this.poseField = value;
            }
        }
        
        /// <remarks/>
        public sbyte truncated {
            get {
                return this.truncatedField;
            }
            set {
                this.truncatedField = value;
            }
        }
        
        /// <remarks/>
        public sbyte difficult {
            get {
                return this.difficultField;
            }
            set {
                this.difficultField = value;
            }
        }
        
        /// <remarks/>
        public annotationObjectBndbox bndbox {
            get {
                return this.bndboxField;
            }
            set {
                this.bndboxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class annotationObjectBndbox {
        
        private short xminField;
        
        private short yminField;
        
        private short xmaxField;
        
        private short ymaxField;
        
        /// <remarks/>
        public short xmin {
            get {
                return this.xminField;
            }
            set {
                this.xminField = value;
            }
        }
        
        /// <remarks/>
        public short ymin {
            get {
                return this.yminField;
            }
            set {
                this.yminField = value;
            }
        }
        
        /// <remarks/>
        public short xmax {
            get {
                return this.xmaxField;
            }
            set {
                this.xmaxField = value;
            }
        }
        
        /// <remarks/>
        public short ymax {
            get {
                return this.ymaxField;
            }
            set {
                this.ymaxField = value;
            }
        }
    }
}
